language: python
python:
  - "3.7"

services:
  - docker

before_script:
  - pip install docker-compose
  - docker-compose up -d --build

script:
  - docker-compose run --rm app sh -c "python manage.py test && flake8"

after_script:
  - docker-compose down